name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history

      - name: Update to latest main
        run: |
          echo "Fetching latest changes..."
          git fetch origin main
          echo "Resetting to origin/main..."
          git reset --hard origin/main

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login fastapiregistry001.azurecr.io -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t fastapiregistry001.azurecr.io/fastapi-nginx-app:latest .

      - name: Push the Docker image
        run: docker push fastapiregistry001.azurecr.io/fastapi-nginx-app:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: fast-api-002
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'fastapiregistry001.azurecr.io/fastapi-nginx-app:latest'

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Restart web app and verify deployment
        run: |
          # Restart the web app
          echo "Restarting web app..."
          az webapp restart --name fast-api-002 --resource-group fastapi-book-app_group

          # Wait for the restart to complete
          echo "Waiting for restart to complete..."
          sleep 30

           # Verify deployment
          echo "Verifying deployment..."
          APP_URL="https://fast-api-002.azurewebsites.net"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" $APP_URL)

          if [ $HTTP_STATUS -eq 200 ]; then
            echo "Deployment verified successfully - HTTP Status: $HTTP_STATUS"
          else
            echo "Deployment verification failed - HTTP Status: $HTTP_STATUS"
            exit 1
          fi