name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login fastapiregistry001.azurecr.io -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t fastapiregistry001.azurecr.io/fastapi-nginx-app:latest .

      - name: Push the Docker image
        run: docker push fastapiregistry001.azurecr.io/fastapi-nginx-app:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: fast-api-002
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'fastapiregistry001.azurecr.io/fastapi-nginx-app:latest'

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Restart Azure Web App
        run: |
          echo "Restarting Azure Web App..."
          az webapp restart --name fast-api-002 --resource-group fastapi-book-app_group